spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5431/demo
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: MyVerySecurePassword
  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

config:
  security:
    secret: 388c81c79cada4abd82f6cd6a1b76de8eb0c156009f98137e4c41064430eabdd
    expiration: 3600000
#    expiration: 30000
    refresh-token-expiration: 3
  pagination:
    base-url: http://localhost:8080/api/v1
    uri:
      product: /products/paginated
      stock: /stocks/paginated
      supplier: /suppliers/paginated
      user: /users/paginated
      order: /orders/paginated
  json-placeholder:
    base-url: https://jsonplaceholder.typicode.com
    uri:
      posts: posts
      comments: /comments
  telegram:
    base-url: https://api.telegram.org/bot{TOKEN}/sendMessage
    token: 8495775301:AAFZo6Aq0M_FRhyh7iKAS6W_C7b9UbhntkQ
    chat-id: -5090045239